//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmCatalog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmCatalog.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация об актёре.
        /// </summary>
        internal static string ActorInformation {
            get {
                return ResourceManager.GetString("ActorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя:.
        /// </summary>
        internal static string ActorName {
            get {
                return ResourceManager.GetString("ActorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актёры.
        /// </summary>
        internal static string ActorsLabel {
            get {
                return ResourceManager.GetString("ActorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возрастное ограничение:.
        /// </summary>
        internal static string AgeLimit {
            get {
                return ResourceManager.GetString("AgeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автосохранение:.
        /// </summary>
        internal static string Autosave {
            get {
                return ResourceManager.GetString("Autosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Биография:.
        /// </summary>
        internal static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения:.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет графиков:.
        /// </summary>
        internal static string ChartsColor {
            get {
                return ResourceManager.GetString("ChartsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избранное.
        /// </summary>
        internal static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о фильме.
        /// </summary>
        internal static string FilmInformation {
            get {
                return ResourceManager.GetString("FilmInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        internal static string FilmName {
            get {
                return ResourceManager.GetString("FilmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильмы:.
        /// </summary>
        internal static string Films {
            get {
                return ResourceManager.GetString("Films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильмы.
        /// </summary>
        internal static string FilmsLabel {
            get {
                return ResourceManager.GetString("FilmsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО:.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр:.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфографика.
        /// </summary>
        internal static string Infographics {
            get {
                return ResourceManager.GetString("Infographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        internal static string MenuPage {
            get {
                return ResourceManager.GetString("MenuPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый актёр.
        /// </summary>
        internal static string NewActor {
            get {
                return ResourceManager.GetString("NewActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый фильм.
        /// </summary>
        internal static string NewFilm {
            get {
                return ResourceManager.GetString("NewFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый режиссёр.
        /// </summary>
        internal static string NewProducer {
            get {
                return ResourceManager.GetString("NewProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к картинке:.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярные жанры.
        /// </summary>
        internal static string PopularGenres {
            get {
                return ResourceManager.GetString("PopularGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режиссёр:.
        /// </summary>
        internal static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о режиссёре.
        /// </summary>
        internal static string ProducerInformation {
            get {
                return ResourceManager.GetString("ProducerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режиссёры.
        /// </summary>
        internal static string ProducersLabel {
            get {
                return ResourceManager.GetString("ProducersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг:.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год выпуска:.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В главных ролях:.
        /// </summary>
        internal static string Starring {
            get {
                return ResourceManager.GetString("Starring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В избранное.
        /// </summary>
        internal static string ToFavourites {
            get {
                return ResourceManager.GetString("ToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет панели инструментов:.
        /// </summary>
        internal static string ToolBarColor {
            get {
                return ResourceManager.GetString("ToolBarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет текста панели инструментов:.
        /// </summary>
        internal static string ToolBarTextColor {
            get {
                return ResourceManager.GetString("ToolBarTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Википедия.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
    }
}
